// Generated by CoffeeScript 1.3.1
(function() {
  var music, pause_button;

  music = document.getElementById("music");

  music.status = "play";

  pause_button = document.getElementById("pause_button");

  pause_button.onclick = function() {
    if (music.status === "pause") {
      music.status = "play";
      return music.play();
    } else {
      music.status = "pause";
      return music.pause();
    }
  };

}).call(this);
